repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: no-commit-to-branch
  - id: check-merge-conflict
- repo: local
  hooks:
    - id: run-python-script
      name: Verify headers
      entry: python tools/verify_headers.py pec_runtime test tools
      language: system
      types: [python]
      exclude: ^docs
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.4
  hooks:
    - id: ruff  # Ruff's linter.
      language_version: python3.11
    - id: ruff-format  # Ruff's formatter.
      language_version: python3.11